#+title: geocompose
#+description: A library for representing geographical regions as a set of addresses. Intended for use in redistricting.

#+caption: 
[[file:https://github.com/InnovativeInventor/geocompose/workflows/Python%20testing%20and%20linting/badge.svg]]
#+caption: 
[[file:https://codecov.io/gh/InnovativeInventor/geocompose/branch/master/graph/badge.svg]]

* Overview
  Geocompose is an implementation of an address-based presentation of geographical regions (e.g. voter precincts or districts).

* Install
  To install, run:
  
 #+begin_src bash
   poetry install
   pip install git+https://github.com/Toblerity/Shapely.git
 #+end_src 
  
 Currently, this depends on Shapely 1.8, which isn't out yet (which is why we build from master).

* Operations Supported (for shapefiles)

- merge operation
- chunking
- diff calculations
- Voronoi diagram creation (to visualize, mostly)


The diff operation is intended primarily for visualization purposes.
If the intersection between the two regions is greater than half of the size of either region, then the the two regions are considered to be the same. 
The difference is the [[https://shapely.readthedocs.io/en/latest/manual.html#object.symmetric_difference][symmetric difference]] between the two regions.
If not, the intersection of the two regions is the difference.
Finally, if one of the regions completely contains the other, the symmetric difference is used.
