#+title: geocompose
#+description: A library for representing geographical regions as a set of addresses. Intended for use in redistricting.


* Overview

* Operations

** Merge Operation
   To merge, the address containing the most information when parsed (using libpostal) will added to the output address.
   An address-location pair is considered a duplicate if two conditions are satisfied:
   
   1. The two addresses normalize to the same (or similar) string using libpostal
   2. The two addresses are geographically within 1 kilometer of each other


** Diff Operation (from and address-based representation)
   The diff operation is intended primarily for visualization purposes.
   
   If the intersection between the two regions is greater than half of the size of either region, then the the two regions are considered to be the same.
   The difference is the [[https://shapely.readthedocs.io/en/latest/manual.html#object.symmetric_difference][symmetric difference]] between the two regions.

   If not, the intersection of the two regions is the difference.

   Finally, if one of the regions completely contains the other, the symmetric difference is used.

** Diff Operation (from a polygon representation)
   The diff between two shapefiles are calculated by first converting to an address-based representation, then utilizing the previously defined diff operation on the address-based representation.

** Voronoi Diagram
   In order to visualize an address-based representation of districts better, a voronoi diagram can be used to create a polygon representation of the geographical region.
